baseURL: "https://OSOFlipping.com"
languageCode: en-us
title: OSOFlipping
theme: PaperMod

params:

  defaultTheme: light
  disableThemeToggle: true

  homeInfoParams:
      Title: OSOFlipping - Learn the Flipping Business
      Content: Unlock the Secret to Flipping! Learn how to make money with small items like household appliances, iPhones, and more. Comprehensive courses and expert advice on eBay selling, Facebook Marketplace, and more. Start your journey to financial freedom. Click now to become a pro flipper!.
      
  socialIcons:
  Name: facebook
  Url: “https://facebook.com/”
  Name: twitter
  Url: “https://twitter.com/”

  cover: 
      linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true




menu: 
  main: 
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10

    - identifier: contact
      name: Contact
      url: /contact
      weight: 60



markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false